apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-updater

# Para criar um Service Account no Kubernetes que tenha permissões para atualizar o ConfigMap, precisa definir uma Role e um RoleBinding que conceda essas permissões ao Service Account. 

# Com um ConfigMap criado chamado sftp-users agora vou criar um Service Account chamado configmap-updater que possa atualizar esse ConfigMap.

# passos para criar o Service Account, a Role e o RoleBinding:

# Criado o Service Account: configmap-updater-serviceaccount.yaml