apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-local
  labels:
    app.kubernetes.io/name: sftp-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sftp-local
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sftp-local
    spec:
      containers:
        - name: sftp-local
          image: atmoz/sftp # imagem que tem a estrutura do sftp
          imagePullPolicy: IfNotPresent #significa que o Kubernetes verificará se a imagem já está presente no nó onde o pod está sendo implantado.
          # imagePullPolicy: Always - Sempre buscar a imagem mais recente
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: sftp-pv
              mountPath: "/home" # volume/sftp local criado no minikube ssh contém usuarios foo bar baz
              subPath: ""
            - mountPath: /etc/sftp # users.conf mapeado do configmap
              name: usersconf
              readOnly: true
      volumes:
        - name: sftp-pv
          hostPath:
           path: /volume/sftp # volume criado no minikube ssh 
        - name: usersconf
          configMap: # contem informações dos usuario
            defaultMode: 0420
            name: sftp-users
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-local-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sftp-local
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
