apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftp-local-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  mountOptions:
    - hard
    - rsize=1048576
    - wsize=1048576
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.server }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-local-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: sftp-local-volume
  storageClassName: "standard"