apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftp-local-volume
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sftp/data/"

#O volume terá o nome “sftp-local-volume”, do tipo local (significa que será montado localmente — no cluster ),
#pertencendo a classe manual, com capacidade de armazenamento de 2Gi, o modo de acesso ReadWriteOnce 
#(o volume pode ser montado como leitura-gravação por um único node), e dentro de cluster os dados do volume 
#serão guardados no path “/mnt/sftp/data/”.

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-local-volume-claim
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

#Os detalhes do volume_claim significam que declara-se uma necessidade de armazenamento de 1Gi
#e um modo de acesso de ReadWriteOnce, o que significa que o volume pode ser montado 
#como leitura-gravação por um único node.